name = "ai-voice-assistant"
main = "workers.js"
compatibility_date = "2024-01-01"

[env.production]
name = "ai-voice-assistant"

[env.staging]
name = "ai-voice-assistant-staging"

# 环境变量配置
[vars]
ENVIRONMENT = "production"

# 如果需要KV存储，可以取消注释
# [[kv_namespaces]]
# binding = "AI_ASSISTANT_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
